#!/bin/sh
#
#  Convert .svg files to .png using svgexport.
#
#  npm install -g svgexport
#

if hash svgexport; then

  for file in $1*.svg; do
    if [[ $file != 'none'* ]]; then
      svgexport $file `echo $file | sed s/.svg/.png/`
    fi  
  done

fi
