#!/bin/sh
#
#  Create needed copies of deprecated and duplicate files.
#

rm -f boy0.png && cp -f boy_3.png boy0.png
rm -f boy0.svg && cp -f boy_3.svg boy0.svg
rm -f boy1.png && cp -f boy_2.png boy1.png
rm -f boy1.svg && cp -f boy_2.svg boy1.svg
rm -f boy2.png && cp -f boy_1.png boy2.png
rm -f boy2.svg && cp -f boy_1.svg boy2.svg
rm -f boy3.png && cp -f boy_4.png boy3.png
rm -f boy3.svg && cp -f boy_4.svg boy3.svg
rm -f boy4.png && cp -f boy_3.png boy4.png
rm -f boy4.svg && cp -f boy_3.svg boy4.svg
rm -f boy5.png && cp -f boy_4.png boy5.png
rm -f boy5.svg && cp -f boy_4.svg boy5.svg
rm -f boy6.png && cp -f boy_2.png boy6.png
rm -f boy6.svg && cp -f boy_2.svg boy6.svg
rm -f boy7.png && cp -f boy_2.png boy7.png
rm -f boy7.svg && cp -f boy_2.svg boy7.svg

rm -f child1.png && cp -f girl_1.png child1.png
rm -f child1.svg && cp -f girl_1.svg child1.svg
rm -f child2.png && cp -f girl_2.png child2.png
rm -f child2.svg && cp -f girl_2.svg child2.svg

rm -f child1-off.png && cp -f child1.png child1-off.png
rm -f child1-off.svg && cp -f child1.svg child1-off.svg
rm -f child2-off.png && cp -f child2.png child2-off.png
rm -f child2-off.svg && cp -f child2.svg child2-off.svg

rm -f garagedoor-ajar.png && cp -f garagedoor-70.png garagedoor-ajar.png
rm -f garagedoor-ajar.svg && cp -f garagedoor-70.svg garagedoor-ajar.svg
rm -f garagedoor-closed.png && cp -f garagedoor-100.png garagedoor-closed.png
rm -f garagedoor-closed.svg && cp -f garagedoor-100.svg garagedoor-closed.svg
rm -f garagedoor-open.png && cp -f garagedoor-0.png garagedoor-open.png
rm -f garagedoor-open.svg && cp -f garagedoor-0.svg garagedoor-open.svg
rm -f garagedoor.png && cp -f garagedoor-ajar.png garagedoor.png
rm -f garagedoor.svg && cp -f garagedoor-ajar.svg garagedoor.svg

rm -f garden2.png && cp -f garden.png garden2.png
rm -f garden2.svg && cp -f garden.svg garden2.svg

rm -f garden3.png && cp -f garden.png garden3.png
rm -f garden3.svg && cp -f garden.svg garden3.svg

rm -f group.png && cp -f house.png group.png
rm -f group.svg && cp -f house.svg group.svg
rm -f house-off.png && cp -f house.png house-off.png
rm -f house-off.svg && cp -f house.svg house-off.svg

rm -f heating-off.png && cp -f heating-0.png heating-off.png
rm -f heating-off.svg && cp -f heating-0.svg heating-off.svg
rm -f heating-on.png && cp -f heating-100.png heating-on.png
rm -f heating-on.svg && cp -f heating-100.svg heating-on.svg
rm -f heating.png && cp -f heating-on.png heating.png
rm -f heating.svg && cp -f heating-on.svg heating.svg

rm -f light-off.png && cp -f slider-0.png light-off.png
rm -f light-off.svg && cp -f slider-0.svg light-off.svg
rm -f light-on.png && cp -f slider-100.png light-on.png
rm -f light-on.svg && cp -f slider-100.svg light-on.svg
rm -f slider.png && cp -f slider-100.png slider.png
rm -f slider.svg && cp -f slider-100.svg slider.svg

rm -f lock.png && cp -f lock-closed.png lock.png
rm -f lock.svg && cp -f lock-closed.svg lock.svg

rm -f rollershutter.png && cp -f rollershutter-70.png rollershutter.png
rm -f rollershutter.svg && cp -f rollershutter-70.svg rollershutter.svg

rm -f shield-2.png && cp -f shield-1.png shield-2.png
rm -f shield-2.svg && cp -f shield-1.svg shield-2.svg

rm -f wardrobe2.png && cp -f wardrobe.png wardrobe2.png
rm -f wardrobe2.svg && cp -f wardrobe.svg wardrobe2.svg