#!/bin/sh
#
#  Convert .svg files to .png using svgexport.
#
#  Pass an argument to only convert files starting with given string.
#

if hash svgexport; then

  for file in $1*.svg; do
    if [[ $file != 'none'* ]]; then
      svgexport $file `echo $file | sed s/.svg/.png/`
    fi  
  done

# elif hash qlmanage; then
# 	
#   ls | grep -E '.png.png$|.svg.png$' | xargs rm
# 
#   ls | grep '.svg$' | grep -Ev 'none.svg$' | awk '{print $NF}' | xargs qlmanage -t -o .
#   
#   for file in *.svg.png
#   do
#     mv $file `echo $file | sed s/.svg//`
#   done

elif hash npm; then

    npm install -g svgexport

else

    echo "Please install 'svgexport' using npm:"
    echo "npm install -g svgexport"

fi